// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSwRT5SFk4CswjXEBTK4dFtIOUPfZYbuk',
    appId: '1:512216865859:web:9c2c823f8540cfc54508f6',
    messagingSenderId: '512216865859',
    projectId: 'flutter-voyager',
    authDomain: 'flutter-voyager.firebaseapp.com',
    storageBucket: 'flutter-voyager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJNQwIfbdW4ObkOP-aq4l39wDvXE8XdQ',
    appId: '1:512216865859:android:8c1150103c977cb14508f6',
    messagingSenderId: '512216865859',
    projectId: 'flutter-voyager',
    storageBucket: 'flutter-voyager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZj8MMyzpYDRNIBtQmzeqOwkPoX7L2vQc',
    appId: '1:512216865859:ios:2acc55c75a9ba2e94508f6',
    messagingSenderId: '512216865859',
    projectId: 'flutter-voyager',
    storageBucket: 'flutter-voyager.appspot.com',
    iosClientId: '512216865859-h0sau6gdj3t9168d3ai5a6l4e8jtois7.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZj8MMyzpYDRNIBtQmzeqOwkPoX7L2vQc',
    appId: '1:512216865859:ios:2acc55c75a9ba2e94508f6',
    messagingSenderId: '512216865859',
    projectId: 'flutter-voyager',
    storageBucket: 'flutter-voyager.appspot.com',
    iosClientId: '512216865859-h0sau6gdj3t9168d3ai5a6l4e8jtois7.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyager',
  );
}
